### ISSUE TITLE
Is there a minimum version of Tomcat that this works with?

### ISSUE THREAD

**Issue by edhill** [simplicityitself/Mongo-Tomcat-Sessions#1]
I'm trying to get this working under a Tomcat 5.5 install, and I get the following error each time on startup

java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:295)
    at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:433)
Caused by: java.lang.NullPointerException
    at org.apache.catalina.startup.Catalina.await(Catalina.java:616)
    at org.apache.catalina.startup.Catalina.start(Catalina.java:576)
    ... 6 more

I can not been able to figure out the problem yet, but it seems to be associated with the Valve, if I comment out the Valve in my server.xml, I get startup, but I'm not seeing hooks into the SessionManager code

**Comment by dawsonsystems** [comment]
Hi there.  

I've tested this against tomcat 6.

David.

**Comment by edhill** [comment]
Thanks, I'll see if I can make it work under 5.5 on my own and update this comment if I can do so

**Comment by edhill** [comment]
Just to followup, I was able to get it working successfully under 5.5.35, my previous issue was just not getting the correct jar files in the correct places.

Thanks for writing this, it looks like it will be a much simpler solution to implement than some alternatives.

**Comment by dawsonsystems** [comment]
Excellent, good to know!
I've had this in production on a clients application for around 6 months.
No issues so far and its helped avoid some outages (slicehost send to be
getting flaky these days).
If you have any suggestions or feature requests, feel free to open an issue
here.
On Feb 14, 2012 9:53 PM, "Ed Hill" <
reply@reply.github.com>
wrote:
